name = "Minecraft Modpack"
author = "Joaqim"
version = "v2024.11.28-rc4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd78f5f32cfc9ac6a948a71b861405fad4ddc512262f29617289ac9a293815df"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
