name = "Minecraft Modpack"
author = "Joaqim"
version = "v2025.05.03-rc4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdbc6fd457311d91e9d9f881b6e7a12b8725b439906fb29fcda518a9f9e400f1"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4"]
