name = "Joaqim's Minecraft Modpack"
author = "Joaqim Planstedt <mail@joaqim.xyz>"
version = "1.0.1-rc2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2762ecb88a7a428a81333286d2ee55f7ec9e3bfa4438507ed3a7d6336acf0c7"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
