name = "Gjewt"
author = "Joaqim"
version = "2024.07.19-rc6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d705aa7b1cbb72b6f7d44a0c43db9158a24c7e8c3363043ae801d32aaaf9d91"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
