name = "Minecraft Modpack"
author = "Joaqim"
version = "v2025.04.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "592b39007a53f574027f8c0753974e3ad09fb6407e47aca47b1fdf89d5416afa"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
