name = "Minecraft Modpack"
author = "Joaqim"
version = "v2025.11.22-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "481c467ec1abc0b4626b86dae5f386ff0312b73f817a193b09aaa298b28e66e0"

[versions]
fabric = "0.134.0"
minecraft = "1.21.9"

[options]
acceptable-game-versions = ["1.21.9", "1.21.x"]
