name = "Minecraft Modpack"
author = "Joaqim"
version = "v2025.05.15-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd4fb6ff2993c6ee1c0c462024b1407c51d4e6b3846d7b30eafa683166924c84"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4", "1.21-1.21.1", "1.21", "1.21.1"]
