name = "Minecraft Modpack"
author = "Joaqim"
version = "v2025.05.03-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02e201c4ca1bc04edc9b86b754515c344fbb2cae2a2b7b7348f89740920db871"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
