name = "Joaqim's Minecraft Modpack"
author = "Joaqim Planstedt <mail@joaqim.xyz>"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f1cc86315ce713a85319f284e7fc42ec5f3710bd73edeb8f5bbc85d17f7593a"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
