name = "Minecraft Modpack"
author = "Joaqim"
version = "v2025.04.21-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd99c207bf42289d8bbb0faddf49982ff72d9c71b1b85623182cb94e2e22c8ea"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
