name = "Minecraft Modpack"
author = "Joaqim"
version = "v2025.02.22-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92b321fbdeff43b85f3d2b147d5ed52fd100e069153f42f19a2766d0372c8357"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
