name = "Minecraft Modpack"
author = "Joaqim"
version = "2024.11.28-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5da5654b29f9f06a2c29b24ecaf4d6fd376a02bc59e0f8ac216b8588f3717484"

[versions]
forge = "53.0.25"
minecraft = "1.21.3"
