name = "Minecraft Modpack"
author = "Joaqim"
version = "v2025.07.05-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57587dfd4328a51b0b1685f5b5add8f1d46428ee29aecfe6ad62fdf08b935f7a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"

[options]
acceptable-game-versions = ["1.21.6"]
