name = "Minecraft Modpack"
author = "Joaqim"
version = "v2025.05.11-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1d71f147f7a2d5ad2dec00514b10a1d6744d46a6d16c52b3775424b93d23889"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3", "1.21.4"]
